-- Nettoyage des doublons (exemple pour CCG et OTSC)
DELETE FROM organization WHERE id IN ('org_gulf_cooperation', 'org_csto');

-- Complétion des membres pour les organisations majeures
-- Exemple : CEDEAO (Communauté économique des États de l'Afrique de l'Ouest)
INSERT INTO country_organization (countryid, organizationid, role, dateadhesion) VALUES
  ('benin', 'org_ecowas', 'Membre', '1975-05-28'),
  ('burkina-faso', 'org_ecowas', 'Membre', '1975-05-28'),
  ('cap-vert', 'org_ecowas', 'Membre', '1975-05-28'),
  ('cote-divoire', 'org_ecowas', 'Membre', '1975-05-28'),
  ('gambie', 'org_ecowas', 'Membre', '1975-05-28'),
  ('ghana', 'org_ecowas', 'Membre', '1975-05-28'),
  ('guinee', 'org_ecowas', 'Membre', '1975-05-28'),
  ('guinee-bissau', 'org_ecowas', 'Membre', '1975-05-28'),
  ('liberia', 'org_ecowas', 'Membre', '1975-05-28'),
  ('mali', 'org_ecowas', 'Membre', '1975-05-28'),
  ('niger', 'org_ecowas', 'Membre', '1975-05-28'),
  ('nigeria', 'org_ecowas', 'Membre', '1975-05-28'),
  ('senegal', 'org_ecowas', 'Membre', '1975-05-28'),
  ('sierra-leone', 'org_ecowas', 'Membre', '1975-05-28'),
  ('togo', 'org_ecowas', 'Membre', '1975-05-28');

-- Exemple : SADC (Communauté de développement d'Afrique australe)
INSERT INTO country_organization (countryid, organizationid, role, dateadhesion) VALUES
  ('angola', 'org_sadc', 'Membre', '1990-08-17'),
  ('botswana', 'org_sadc', 'Membre', '1990-08-17'),
  ('comores', 'org_sadc', 'Membre', '2017-08-17'),
  ('rdc', 'org_sadc', 'Membre', '1997-08-17'),
  ('eswatini', 'org_sadc', 'Membre', '1990-08-17'),
  ('lesotho', 'org_sadc', 'Membre', '1990-08-17'),
  ('madagascar', 'org_sadc', 'Membre', '2004-08-17'),
  ('malawi', 'org_sadc', 'Membre', '1990-08-17'),
  ('maurice', 'org_sadc', 'Membre', '1995-08-17'),
  ('mozambique', 'org_sadc', 'Membre', '1992-08-17'),
  ('namibie', 'org_sadc', 'Membre', '1990-08-17'),
  ('afrique-du-sud', 'org_sadc', 'Membre', '1994-08-17'),
  ('tanzanie', 'org_sadc', 'Membre', '1990-08-17'),
  ('zambie', 'org_sadc', 'Membre', '1990-08-17'),
  ('zimbabwe', 'org_sadc', 'Membre', '1990-08-17');

-- Exemple : OIF (Organisation internationale de la Francophonie)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('france', 'org_francophonie', 'Membre'),
  ('canada', 'org_francophonie', 'Membre'),
  ('belgique', 'org_francophonie', 'Membre'),
  ('suisse', 'org_francophonie', 'Membre'),
  ('cote-divoire', 'org_francophonie', 'Membre'),
  ('senegal', 'org_francophonie', 'Membre'),
  ('burkina-faso', 'org_francophonie', 'Membre'),
  ('benin', 'org_francophonie', 'Membre'),
  ('togo', 'org_francophonie', 'Membre'),
  ('niger', 'org_francophonie', 'Membre'),
  ('mali', 'org_francophonie', 'Membre'),
  ('tchad', 'org_francophonie', 'Membre'),
  ('cameroun', 'org_francophonie', 'Membre'),
  ('madagascar', 'org_francophonie', 'Membre'),
  ('vietnam', 'org_francophonie', 'Membre');

-- Exemple : UA (Union Africaine)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('afrique-du-sud', 'org_african_union', 'Membre'),
  ('algerie', 'org_african_union', 'Membre'),
  ('angola', 'org_african_union', 'Membre'),
  ('benin', 'org_african_union', 'Membre'),
  ('botswana', 'org_african_union', 'Membre'),
  ('burkina-faso', 'org_african_union', 'Membre'),
  ('burundi', 'org_african_union', 'Membre'),
  ('cameroun', 'org_african_union', 'Membre'),
  ('cap-vert', 'org_african_union', 'Membre'),
  ('centrafrique', 'org_african_union', 'Membre'),
  ('comores', 'org_african_union', 'Membre'),
  ('congo', 'org_african_union', 'Membre'),
  ('rdc', 'org_african_union', 'Membre'),
  ('cote-divoire', 'org_african_union', 'Membre'),
  ('djibouti', 'org_african_union', 'Membre'),
  ('egypte', 'org_african_union', 'Membre'),
  ('erythree', 'org_african_union', 'Membre'),
  ('ethiopie', 'org_african_union', 'Membre'),
  ('gabon', 'org_african_union', 'Membre'),
  ('gambie', 'org_african_union', 'Membre'),
  ('ghana', 'org_african_union', 'Membre'),
  ('guinee', 'org_african_union', 'Membre'),
  ('guinee-bissau', 'org_african_union', 'Membre'),
  ('guinee-equatoriale', 'org_african_union', 'Membre'),
  ('kenya', 'org_african_union', 'Membre'),
  ('lesotho', 'org_african_union', 'Membre'),
  ('liberia', 'org_african_union', 'Membre'),
  ('libye', 'org_african_union', 'Membre'),
  ('madagascar', 'org_african_union', 'Membre'),
  ('malawi', 'org_african_union', 'Membre'),
  ('mali', 'org_african_union', 'Membre'),
  ('maroc', 'org_african_union', 'Membre'),
  ('maurice', 'org_african_union', 'Membre'),
  ('mauritanie', 'org_african_union', 'Membre'),
  ('mozambique', 'org_african_union', 'Membre'),
  ('namibie', 'org_african_union', 'Membre'),
  ('niger', 'org_african_union', 'Membre'),
  ('nigeria', 'org_african_union', 'Membre'),
  ('ouganda', 'org_african_union', 'Membre'),
  ('rwanda', 'org_african_union', 'Membre'),
  ('sao-tome-et-principe', 'org_african_union', 'Membre'),
  ('senegal', 'org_african_union', 'Membre'),
  ('seychelles', 'org_african_union', 'Membre'),
  ('sierra-leone', 'org_african_union', 'Membre'),
  ('somalie', 'org_african_union', 'Membre'),
  ('soudan', 'org_african_union', 'Membre'),
  ('soudan-du-sud', 'org_african_union', 'Membre'),
  ('tanzanie', 'org_african_union', 'Membre'),
  ('tchad', 'org_african_union', 'Membre'),
  ('togo', 'org_african_union', 'Membre'),
  ('tunisie', 'org_african_union', 'Membre'),
  ('zambie', 'org_african_union', 'Membre'),
  ('zimbabwe', 'org_african_union', 'Membre');

-- (À compléter pour les autres organisations majeures : OMC, ONU, ASEAN, etc.) 