-- Script pour compléter les organisations par paquets
-- Batch 1 : Corrections et organisations majeures

-- 1. Correction des identifiants de pays
-- 2. Ajout des membres pour les organisations majeures

-- ONU (Organisation des Nations Unies) - Tous les pays souverains
INSERT INTO country_organization (countryid, organizationid, role) 
SELECT c.id, 'onu', 'Membre'
FROM country c
WHERE c.id NOT IN (
  SELECT co.countryid FROM country_organization co WHERE co.organizationid = 'onu'
)
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OMC (Organisation mondiale du commerce) - Membres actuels
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('afghanistan', 'org_wto', 'Membre'),
  ('afrique-du-sud', 'org_wto', 'Membre'),
  ('albanie', 'org_wto', 'Membre'),
  ('allemagne', 'org_wto', 'Membre'),
  ('angola', 'org_wto', 'Membre'),
  ('arabie-saoudite', 'org_wto', 'Membre'),
  ('argentine', 'org_wto', 'Membre'),
  ('australie', 'org_wto', 'Membre'),
  ('autriche', 'org_wto', 'Membre'),
  ('bahamas', 'org_wto', 'Membre'),
  ('bangladesh', 'org_wto', 'Membre'),
  ('barbade', 'org_wto', 'Membre'),
  ('belgique', 'org_wto', 'Membre'),
  ('belize', 'org_wto', 'Membre'),
  ('benin', 'org_wto', 'Membre'),
  ('bolivie', 'org_wto', 'Membre'),
  ('botswana', 'org_wto', 'Membre'),
  ('bresil', 'org_wto', 'Membre'),
  ('brunei', 'org_wto', 'Membre'),
  ('bulgarie', 'org_wto', 'Membre'),
  ('burkina-faso', 'org_wto', 'Membre'),
  ('burundi', 'org_wto', 'Membre'),
  ('cambodge', 'org_wto', 'Membre'),
  ('cameroun', 'org_wto', 'Membre'),
  ('canada', 'org_wto', 'Membre'),
  ('cape-verde', 'org_wto', 'Membre'),
  ('chili', 'org_wto', 'Membre'),
  ('chine', 'org_wto', 'Membre'),
  ('colombie', 'org_wto', 'Membre'),
  ('comores', 'org_wto', 'Membre'),
  ('congo', 'org_wto', 'Membre'),
  ('costa-rica', 'org_wto', 'Membre'),
  ('cote-divoire', 'org_wto', 'Membre'),
  ('croatie', 'org_wto', 'Membre'),
  ('cuba', 'org_wto', 'Membre'),
  ('danemark', 'org_wto', 'Membre'),
  ('djibouti', 'org_wto', 'Membre'),
  ('egypte', 'org_wto', 'Membre'),
  ('el-salvador', 'org_wto', 'Membre'),
  ('emirats-arabes-unis', 'org_wto', 'Membre'),
  ('equateur', 'org_wto', 'Membre'),
  ('erythree', 'org_wto', 'Membre'),
  ('espagne', 'org_wto', 'Membre'),
  ('estonie', 'org_wto', 'Membre'),
  ('etats-unis', 'org_wto', 'Membre'),
  ('ethiopie', 'org_wto', 'Membre'),
  ('fidji', 'org_wto', 'Membre'),
  ('finlande', 'org_wto', 'Membre'),
  ('france', 'org_wto', 'Membre'),
  ('gabon', 'org_wto', 'Membre'),
  ('gambie', 'org_wto', 'Membre'),
  ('georgie', 'org_wto', 'Membre'),
  ('ghana', 'org_wto', 'Membre'),
  ('grece', 'org_wto', 'Membre'),
  ('guatemala', 'org_wto', 'Membre'),
  ('guinee', 'org_wto', 'Membre'),
  ('guinee-bissau', 'org_wto', 'Membre'),
  ('guinee-equatoriale', 'org_wto', 'Membre'),
  ('guyana', 'org_wto', 'Membre'),
  ('haiti', 'org_wto', 'Membre'),
  ('honduras', 'org_wto', 'Membre'),
  ('hongrie', 'org_wto', 'Membre'),
  ('inde', 'org_wto', 'Membre'),
  ('indonesie', 'org_wto', 'Membre'),
  ('irak', 'org_wto', 'Membre'),
  ('iran', 'org_wto', 'Membre'),
  ('irlande', 'org_wto', 'Membre'),
  ('islande', 'org_wto', 'Membre'),
  ('israel', 'org_wto', 'Membre'),
  ('italie', 'org_wto', 'Membre'),
  ('jamaique', 'org_wto', 'Membre'),
  ('japon', 'org_wto', 'Membre'),
  ('jordanie', 'org_wto', 'Membre'),
  ('kazakhstan', 'org_wto', 'Membre'),
  ('kenya', 'org_wto', 'Membre'),
  ('kirghizistan', 'org_wto', 'Membre'),
  ('laos', 'org_wto', 'Membre'),
  ('lesotho', 'org_wto', 'Membre'),
  ('lettonie', 'org_wto', 'Membre'),
  ('liberia', 'org_wto', 'Membre'),
  ('libye', 'org_wto', 'Membre'),
  ('lituanie', 'org_wto', 'Membre'),
  ('luxembourg', 'org_wto', 'Membre'),
  ('madagascar', 'org_wto', 'Membre'),
  ('malawi', 'org_wto', 'Membre'),
  ('malaisie', 'org_wto', 'Membre'),
  ('maldives', 'org_wto', 'Membre'),
  ('mali', 'org_wto', 'Membre'),
  ('malte', 'org_wto', 'Membre'),
  ('mauritanie', 'org_wto', 'Membre'),
  ('maurice', 'org_wto', 'Membre'),
  ('mexique', 'org_wto', 'Membre'),
  ('moldavie', 'org_wto', 'Membre'),
  ('mongolie', 'org_wto', 'Membre'),
  ('mozambique', 'org_wto', 'Membre'),
  ('myanmar', 'org_wto', 'Membre'),
  ('namibie', 'org_wto', 'Membre'),
  ('nepal', 'org_wto', 'Membre'),
  ('nicaragua', 'org_wto', 'Membre'),
  ('niger', 'org_wto', 'Membre'),
  ('nigeria', 'org_wto', 'Membre'),
  ('norvege', 'org_wto', 'Membre'),
  ('nouvelle-zelande', 'org_wto', 'Membre'),
  ('oman', 'org_wto', 'Membre'),
  ('ouganda', 'org_wto', 'Membre'),
  ('pakistan', 'org_wto', 'Membre'),
  ('panama', 'org_wto', 'Membre'),
  ('papouasie-nouvelle-guinee', 'org_wto', 'Membre'),
  ('paraguay', 'org_wto', 'Membre'),
  ('perou', 'org_wto', 'Membre'),
  ('philippines', 'org_wto', 'Membre'),
  ('pologne', 'org_wto', 'Membre'),
  ('portugal', 'org_wto', 'Membre'),
  ('qatar', 'org_wto', 'Membre'),
  ('rdc', 'org_wto', 'Membre'),
  ('republique-tcheque', 'org_wto', 'Membre'),
  ('roumanie', 'org_wto', 'Membre'),
  ('royaume-uni', 'org_wto', 'Membre'),
  ('rwanda', 'org_wto', 'Membre'),
  ('saint-kitts-et-nevis', 'org_wto', 'Membre'),
  ('saint-lucie', 'org_wto', 'Membre'),
  ('saint-vincent-et-les-grenadines', 'org_wto', 'Membre'),
  ('sao-tome-et-principe', 'org_wto', 'Membre'),
  ('senegal', 'org_wto', 'Membre'),
  ('seychelles', 'org_wto', 'Membre'),
  ('sierra-leone', 'org_wto', 'Membre'),
  ('singapore', 'org_wto', 'Membre'),
  ('slovaquie', 'org_wto', 'Membre'),
  ('slovenie', 'org_wto', 'Membre'),
  ('somalie', 'org_wto', 'Membre'),
  ('soudan', 'org_wto', 'Membre'),
  ('soudan-du-sud', 'org_wto', 'Membre'),
  ('sri-lanka', 'org_wto', 'Membre'),
  ('suisse', 'org_wto', 'Membre'),
  ('suriname', 'org_wto', 'Membre'),
  ('swaziland', 'org_wto', 'Membre'),
  ('syrie', 'org_wto', 'Membre'),
  ('tanzanie', 'org_wto', 'Membre'),
  ('tchad', 'org_wto', 'Membre'),
  ('thailande', 'org_wto', 'Membre'),
  ('togo', 'org_wto', 'Membre'),
  ('tonga', 'org_wto', 'Membre'),
  ('trinite-et-tobago', 'org_wto', 'Membre'),
  ('tunisie', 'org_wto', 'Membre'),
  ('turquie', 'org_wto', 'Membre'),
  ('ukraine', 'org_wto', 'Membre'),
  ('uruguay', 'org_wto', 'Membre'),
  ('vietnam', 'org_wto', 'Membre'),
  ('yemen', 'org_wto', 'Membre'),
  ('zambie', 'org_wto', 'Membre'),
  ('zimbabwe', 'org_wto', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- ASEAN (Association des nations de l'Asie du Sud-Est)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('brunei', 'org_asean', 'Membre'),
  ('cambodge', 'org_asean', 'Membre'),
  ('indonesie', 'org_asean', 'Membre'),
  ('laos', 'org_asean', 'Membre'),
  ('malaisie', 'org_asean', 'Membre'),
  ('myanmar', 'org_asean', 'Membre'),
  ('philippines', 'org_asean', 'Membre'),
  ('singapore', 'org_asean', 'Membre'),
  ('thailande', 'org_asean', 'Membre'),
  ('vietnam', 'org_asean', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OCDE (Organisation de coopération et de développement économiques)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('allemagne', 'org_oecd', 'Membre'),
  ('australie', 'org_oecd', 'Membre'),
  ('autriche', 'org_oecd', 'Membre'),
  ('belgique', 'org_oecd', 'Membre'),
  ('canada', 'org_oecd', 'Membre'),
  ('chili', 'org_oecd', 'Membre'),
  ('colombie', 'org_oecd', 'Membre'),
  ('coree-du-sud', 'org_oecd', 'Membre'),
  ('costa-rica', 'org_oecd', 'Membre'),
  ('danemark', 'org_oecd', 'Membre'),
  ('espagne', 'org_oecd', 'Membre'),
  ('estonie', 'org_oecd', 'Membre'),
  ('etats-unis', 'org_oecd', 'Membre'),
  ('finlande', 'org_oecd', 'Membre'),
  ('france', 'org_oecd', 'Membre'),
  ('grece', 'org_oecd', 'Membre'),
  ('hongrie', 'org_oecd', 'Membre'),
  ('irlande', 'org_oecd', 'Membre'),
  ('islande', 'org_oecd', 'Membre'),
  ('israel', 'org_oecd', 'Membre'),
  ('italie', 'org_oecd', 'Membre'),
  ('japon', 'org_oecd', 'Membre'),
  ('lettonie', 'org_oecd', 'Membre'),
  ('lituanie', 'org_oecd', 'Membre'),
  ('luxembourg', 'org_oecd', 'Membre'),
  ('mexique', 'org_oecd', 'Membre'),
  ('nouvelle-zelande', 'org_oecd', 'Membre'),
  ('norvege', 'org_oecd', 'Membre'),
  ('pays-bas', 'org_oecd', 'Membre'),
  ('pologne', 'org_oecd', 'Membre'),
  ('portugal', 'org_oecd', 'Membre'),
  ('republique-tcheque', 'org_oecd', 'Membre'),
  ('royaume-uni', 'org_oecd', 'Membre'),
  ('slovaquie', 'org_oecd', 'Membre'),
  ('slovenie', 'org_oecd', 'Membre'),
  ('suisse', 'org_oecd', 'Membre'),
  ('suede', 'org_oecd', 'Membre'),
  ('turquie', 'org_oecd', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING; 