-- Batch 2 : Organisations restantes

-- G7 (Groupe des Sept)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('usa', 'g7', 'Membre'),
  ('uk', 'g7', 'Membre'),
  ('france', 'g7', 'Membre'),
  ('germany', 'g7', 'Membre'),
  ('italy', 'g7', 'Membre'),
  ('japan', 'g7', 'Membre'),
  ('canada', 'g7', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- G20 (Groupe des Vingt)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('usa', 'g20', 'Membre'),
  ('china', 'g20', 'Membre'),
  ('japan', 'g20', 'Membre'),
  ('germany', 'g20', 'Membre'),
  ('france', 'g20', 'Membre'),
  ('uk', 'g20', 'Membre'),
  ('italy', 'g20', 'Membre'),
  ('canada', 'g20', 'Membre'),
  ('australia', 'g20', 'Membre'),
  ('brazil', 'g20', 'Membre'),
  ('argentina', 'g20', 'Membre'),
  ('mexico', 'g20', 'Membre'),
  ('india', 'g20', 'Membre'),
  ('indonesia', 'g20', 'Membre'),
  ('south-korea', 'g20', 'Membre'),
  ('saudi-arabia', 'g20', 'Membre'),
  ('south-africa', 'g20', 'Membre'),
  ('turkey', 'g20', 'Membre'),
  ('russia', 'g20', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OPEP (Organisation des pays exportateurs de pétrole)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('saudi-arabia', 'org_opec', 'Membre'),
  ('iran', 'org_opec', 'Membre'),
  ('iraq', 'org_opec', 'Membre'),
  ('kuwait', 'org_opec', 'Membre'),
  ('uae', 'org_opec', 'Membre'),
  ('qatar', 'org_opec', 'Membre'),
  ('libya', 'org_opec', 'Membre'),
  ('algeria', 'org_opec', 'Membre'),
  ('nigeria', 'org_opec', 'Membre'),
  ('angola', 'org_opec', 'Membre'),
  ('gabon', 'org_opec', 'Membre'),
  ('equatorial-guinea', 'org_opec', 'Membre'),
  ('congo', 'org_opec', 'Membre'),
  ('venezuela', 'org_opec', 'Membre'),
  ('ecuador', 'org_opec', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- UE (Union européenne)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('france', 'ue', 'Membre'),
  ('germany', 'ue', 'Membre'),
  ('italy', 'ue', 'Membre'),
  ('spain', 'ue', 'Membre'),
  ('netherlands', 'ue', 'Membre'),
  ('belgium', 'ue', 'Membre'),
  ('austria', 'ue', 'Membre'),
  ('denmark', 'ue', 'Membre'),
  ('finland', 'ue', 'Membre'),
  ('greece', 'ue', 'Membre'),
  ('ireland', 'ue', 'Membre'),
  ('luxembourg', 'ue', 'Membre'),
  ('portugal', 'ue', 'Membre'),
  ('sweden', 'ue', 'Membre'),
  ('czech-republic', 'ue', 'Membre'),
  ('estonia', 'ue', 'Membre'),
  ('latvia', 'ue', 'Membre'),
  ('lithuania', 'ue', 'Membre'),
  ('hungary', 'ue', 'Membre'),
  ('malta', 'ue', 'Membre'),
  ('poland', 'ue', 'Membre'),
  ('slovakia', 'ue', 'Membre'),
  ('slovenia', 'ue', 'Membre'),
  ('cyprus', 'ue', 'Membre'),
  ('bulgaria', 'ue', 'Membre'),
  ('romania', 'ue', 'Membre'),
  ('croatia', 'ue', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OTAN (Organisation du Traité de l'Atlantique Nord)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('usa', 'org_nato', 'Membre'),
  ('uk', 'org_nato', 'Membre'),
  ('france', 'org_nato', 'Membre'),
  ('germany', 'org_nato', 'Membre'),
  ('italy', 'org_nato', 'Membre'),
  ('canada', 'org_nato', 'Membre'),
  ('belgium', 'org_nato', 'Membre'),
  ('netherlands', 'org_nato', 'Membre'),
  ('luxembourg', 'org_nato', 'Membre'),
  ('denmark', 'org_nato', 'Membre'),
  ('norway', 'org_nato', 'Membre'),
  ('iceland', 'org_nato', 'Membre'),
  ('portugal', 'org_nato', 'Membre'),
  ('greece', 'org_nato', 'Membre'),
  ('turkey', 'org_nato', 'Membre'),
  ('spain', 'org_nato', 'Membre'),
  ('poland', 'org_nato', 'Membre'),
  ('czech-republic', 'org_nato', 'Membre'),
  ('hungary', 'org_nato', 'Membre'),
  ('estonia', 'org_nato', 'Membre'),
  ('latvia', 'org_nato', 'Membre'),
  ('lithuania', 'org_nato', 'Membre'),
  ('slovakia', 'org_nato', 'Membre'),
  ('slovenia', 'org_nato', 'Membre'),
  ('bulgaria', 'org_nato', 'Membre'),
  ('romania', 'org_nato', 'Membre'),
  ('croatia', 'org_nato', 'Membre'),
  ('albania', 'org_nato', 'Membre'),
  ('montenegro', 'org_nato', 'Membre'),
  ('north-macedonia', 'org_nato', 'Membre'),
  ('finland', 'org_nato', 'Membre'),
  ('sweden', 'org_nato', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- CEDEAO (Communauté économique des États de l'Afrique de l'Ouest)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('benin', 'org_ecowas', 'Membre'),
  ('burkina-faso', 'org_ecowas', 'Membre'),
  ('cape-verde', 'org_ecowas', 'Membre'),
  ('ivory-coast', 'org_ecowas', 'Membre'),
  ('gambia', 'org_ecowas', 'Membre'),
  ('ghana', 'org_ecowas', 'Membre'),
  ('guinea', 'org_ecowas', 'Membre'),
  ('guinea-bissau', 'org_ecowas', 'Membre'),
  ('liberia', 'org_ecowas', 'Membre'),
  ('mali', 'org_ecowas', 'Membre'),
  ('niger', 'org_ecowas', 'Membre'),
  ('nigeria', 'org_ecowas', 'Membre'),
  ('senegal', 'org_ecowas', 'Membre'),
  ('sierra-leone', 'org_ecowas', 'Membre'),
  ('togo', 'org_ecowas', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- SADC (Communauté de développement d'Afrique australe)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('angola', 'org_sadc', 'Membre'),
  ('botswana', 'org_sadc', 'Membre'),
  ('comoros', 'org_sadc', 'Membre'),
  ('drc', 'org_sadc', 'Membre'),
  ('eswatini', 'org_sadc', 'Membre'),
  ('lesotho', 'org_sadc', 'Membre'),
  ('madagascar', 'org_sadc', 'Membre'),
  ('malawi', 'org_sadc', 'Membre'),
  ('mauritius', 'org_sadc', 'Membre'),
  ('mozambique', 'org_sadc', 'Membre'),
  ('namibia', 'org_sadc', 'Membre'),
  ('south-africa', 'org_sadc', 'Membre'),
  ('tanzania', 'org_sadc', 'Membre'),
  ('zambia', 'org_sadc', 'Membre'),
  ('zimbabwe', 'org_sadc', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OIF (Organisation internationale de la Francophonie)
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('france', 'org_francophonie', 'Membre'),
  ('canada', 'org_francophonie', 'Membre'),
  ('belgium', 'org_francophonie', 'Membre'),
  ('switzerland', 'org_francophonie', 'Membre'),
  ('ivory-coast', 'org_francophonie', 'Membre'),
  ('senegal', 'org_francophonie', 'Membre'),
  ('burkina-faso', 'org_francophonie', 'Membre'),
  ('benin', 'org_francophonie', 'Membre'),
  ('togo', 'org_francophonie', 'Membre'),
  ('niger', 'org_francophonie', 'Membre'),
  ('mali', 'org_francophonie', 'Membre'),
  ('chad', 'org_francophonie', 'Membre'),
  ('cameroon', 'org_francophonie', 'Membre'),
  ('madagascar', 'org_francophonie', 'Membre'),
  ('vietnam', 'org_francophonie', 'Membre'),
  ('laos', 'org_francophonie', 'Membre'),
  ('cambodia', 'org_francophonie', 'Membre'),
  ('lebanon', 'org_francophonie', 'Membre'),
  ('tunisia', 'org_francophonie', 'Membre'),
  ('morocco', 'org_francophonie', 'Membre'),
  ('algeria', 'org_francophonie', 'Membre'),
  ('mauritania', 'org_francophonie', 'Membre'),
  ('gabon', 'org_francophonie', 'Membre'),
  ('congo', 'org_francophonie', 'Membre'),
  ('drc', 'org_francophonie', 'Membre'),
  ('central-african-republic', 'org_francophonie', 'Membre'),
  ('equatorial-guinea', 'org_francophonie', 'Membre'),
  ('djibouti', 'org_francophonie', 'Membre'),
  ('comoros', 'org_francophonie', 'Membre'),
  ('seychelles', 'org_francophonie', 'Membre'),
  ('mauritius', 'org_francophonie', 'Membre'),
  ('cape-verde', 'org_francophonie', 'Membre'),
  ('sao-tome-and-principe', 'org_francophonie', 'Membre'),
  ('guinea', 'org_francophonie', 'Membre'),
  ('guinea-bissau', 'org_francophonie', 'Membre'),
  ('sierra-leone', 'org_francophonie', 'Membre'),
  ('liberia', 'org_francophonie', 'Membre'),
  ('ghana', 'org_francophonie', 'Membre'),
  ('nigeria', 'org_francophonie', 'Membre'),
  ('angola', 'org_francophonie', 'Membre'),
  ('zambia', 'org_francophonie', 'Membre'),
  ('zimbabwe', 'org_francophonie', 'Membre'),
  ('botswana', 'org_francophonie', 'Membre'),
  ('namibia', 'org_francophonie', 'Membre'),
  ('lesotho', 'org_francophonie', 'Membre'),
  ('eswatini', 'org_francophonie', 'Membre'),
  ('mozambique', 'org_francophonie', 'Membre'),
  ('tanzania', 'org_francophonie', 'Membre'),
  ('kenya', 'org_francophonie', 'Membre'),
  ('uganda', 'org_francophonie', 'Membre'),
  ('rwanda', 'org_francophonie', 'Membre'),
  ('burundi', 'org_francophonie', 'Membre'),
  ('ethiopia', 'org_francophonie', 'Membre'),
  ('eritrea', 'org_francophonie', 'Membre'),
  ('somalia', 'org_francophonie', 'Membre'),
  ('sudan', 'org_francophonie', 'Membre'),
  ('south-sudan', 'org_francophonie', 'Membre'),
  ('egypt', 'org_francophonie', 'Membre'),
  ('libya', 'org_francophonie', 'Membre'),
  ('haiti', 'org_francophonie', 'Membre'),
  ('dominican-republic', 'org_francophonie', 'Membre'),
  ('vanuatu', 'org_francophonie', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING; 