-- Script final pour corriger les erreurs et compléter les organisations restantes

-- Correction des identifiants pour la RDC
UPDATE country_organization 
SET countryid = 'democratic-republic-of-congo' 
WHERE countryid = 'drc';

-- SADC (Communauté de développement d'Afrique australe) - Correction
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('angola', 'org_sadc', 'Membre'),
  ('botswana', 'org_sadc', 'Membre'),
  ('comoros', 'org_sadc', 'Membre'),
  ('democratic-republic-of-congo', 'org_sadc', 'Membre'),
  ('eswatini', 'org_sadc', 'Membre'),
  ('lesotho', 'org_sadc', 'Membre'),
  ('madagascar', 'org_sadc', 'Membre'),
  ('malawi', 'org_sadc', 'Membre'),
  ('mauritius', 'org_sadc', 'Membre'),
  ('mozambique', 'org_sadc', 'Membre'),
  ('namibia', 'org_sadc', 'Membre'),
  ('south-africa', 'org_sadc', 'Membre'),
  ('tanzania', 'org_sadc', 'Membre'),
  ('zambia', 'org_sadc', 'Membre'),
  ('zimbabwe', 'org_sadc', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- OIF (Organisation internationale de la Francophonie) - Correction
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('france', 'org_francophonie', 'Membre'),
  ('canada', 'org_francophonie', 'Membre'),
  ('belgium', 'org_francophonie', 'Membre'),
  ('switzerland', 'org_francophonie', 'Membre'),
  ('ivory-coast', 'org_francophonie', 'Membre'),
  ('senegal', 'org_francophonie', 'Membre'),
  ('burkina-faso', 'org_francophonie', 'Membre'),
  ('benin', 'org_francophonie', 'Membre'),
  ('togo', 'org_francophonie', 'Membre'),
  ('niger', 'org_francophonie', 'Membre'),
  ('mali', 'org_francophonie', 'Membre'),
  ('chad', 'org_francophonie', 'Membre'),
  ('cameroon', 'org_francophonie', 'Membre'),
  ('madagascar', 'org_francophonie', 'Membre'),
  ('vietnam', 'org_francophonie', 'Membre'),
  ('laos', 'org_francophonie', 'Membre'),
  ('cambodia', 'org_francophonie', 'Membre'),
  ('lebanon', 'org_francophonie', 'Membre'),
  ('tunisia', 'org_francophonie', 'Membre'),
  ('morocco', 'org_francophonie', 'Membre'),
  ('algeria', 'org_francophonie', 'Membre'),
  ('mauritania', 'org_francophonie', 'Membre'),
  ('gabon', 'org_francophonie', 'Membre'),
  ('congo', 'org_francophonie', 'Membre'),
  ('democratic-republic-of-congo', 'org_francophonie', 'Membre'),
  ('central-african-republic', 'org_francophonie', 'Membre'),
  ('equatorial-guinea', 'org_francophonie', 'Membre'),
  ('djibouti', 'org_francophonie', 'Membre'),
  ('comoros', 'org_francophonie', 'Membre'),
  ('seychelles', 'org_francophonie', 'Membre'),
  ('mauritius', 'org_francophonie', 'Membre'),
  ('cape-verde', 'org_francophonie', 'Membre'),
  ('sao-tome-and-principe', 'org_francophonie', 'Membre'),
  ('guinea', 'org_francophonie', 'Membre'),
  ('guinea-bissau', 'org_francophonie', 'Membre'),
  ('sierra-leone', 'org_francophonie', 'Membre'),
  ('liberia', 'org_francophonie', 'Membre'),
  ('ghana', 'org_francophonie', 'Membre'),
  ('nigeria', 'org_francophonie', 'Membre'),
  ('angola', 'org_francophonie', 'Membre'),
  ('zambia', 'org_francophonie', 'Membre'),
  ('zimbabwe', 'org_francophonie', 'Membre'),
  ('botswana', 'org_francophonie', 'Membre'),
  ('namibia', 'org_francophonie', 'Membre'),
  ('lesotho', 'org_francophonie', 'Membre'),
  ('eswatini', 'org_francophonie', 'Membre'),
  ('mozambique', 'org_francophonie', 'Membre'),
  ('tanzania', 'org_francophonie', 'Membre'),
  ('kenya', 'org_francophonie', 'Membre'),
  ('uganda', 'org_francophonie', 'Membre'),
  ('rwanda', 'org_francophonie', 'Membre'),
  ('burundi', 'org_francophonie', 'Membre'),
  ('ethiopia', 'org_francophonie', 'Membre'),
  ('eritrea', 'org_francophonie', 'Membre'),
  ('somalia', 'org_francophonie', 'Membre'),
  ('sudan', 'org_francophonie', 'Membre'),
  ('south-sudan', 'org_francophonie', 'Membre'),
  ('egypt', 'org_francophonie', 'Membre'),
  ('libya', 'org_francophonie', 'Membre'),
  ('haiti', 'org_francophonie', 'Membre'),
  ('dominican-republic', 'org_francophonie', 'Membre'),
  ('vanuatu', 'org_francophonie', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING;

-- UA (Union Africaine) - Correction avec les bons identifiants
INSERT INTO country_organization (countryid, organizationid, role) VALUES
  ('south-africa', 'org_african_union', 'Membre'),
  ('algeria', 'org_african_union', 'Membre'),
  ('angola', 'org_african_union', 'Membre'),
  ('benin', 'org_african_union', 'Membre'),
  ('botswana', 'org_african_union', 'Membre'),
  ('burkina-faso', 'org_african_union', 'Membre'),
  ('burundi', 'org_african_union', 'Membre'),
  ('cameroon', 'org_african_union', 'Membre'),
  ('cape-verde', 'org_african_union', 'Membre'),
  ('central-african-republic', 'org_african_union', 'Membre'),
  ('comoros', 'org_african_union', 'Membre'),
  ('congo', 'org_african_union', 'Membre'),
  ('democratic-republic-of-congo', 'org_african_union', 'Membre'),
  ('ivory-coast', 'org_african_union', 'Membre'),
  ('djibouti', 'org_african_union', 'Membre'),
  ('egypt', 'org_african_union', 'Membre'),
  ('eritrea', 'org_african_union', 'Membre'),
  ('ethiopia', 'org_african_union', 'Membre'),
  ('gabon', 'org_african_union', 'Membre'),
  ('gambia', 'org_african_union', 'Membre'),
  ('ghana', 'org_african_union', 'Membre'),
  ('guinea', 'org_african_union', 'Membre'),
  ('guinea-bissau', 'org_african_union', 'Membre'),
  ('equatorial-guinea', 'org_african_union', 'Membre'),
  ('kenya', 'org_african_union', 'Membre'),
  ('lesotho', 'org_african_union', 'Membre'),
  ('liberia', 'org_african_union', 'Membre'),
  ('libya', 'org_african_union', 'Membre'),
  ('madagascar', 'org_african_union', 'Membre'),
  ('malawi', 'org_african_union', 'Membre'),
  ('mali', 'org_african_union', 'Membre'),
  ('morocco', 'org_african_union', 'Membre'),
  ('mauritius', 'org_african_union', 'Membre'),
  ('mauritania', 'org_african_union', 'Membre'),
  ('mozambique', 'org_african_union', 'Membre'),
  ('namibia', 'org_african_union', 'Membre'),
  ('niger', 'org_african_union', 'Membre'),
  ('nigeria', 'org_african_union', 'Membre'),
  ('uganda', 'org_african_union', 'Membre'),
  ('rwanda', 'org_african_union', 'Membre'),
  ('sao-tome-and-principe', 'org_african_union', 'Membre'),
  ('senegal', 'org_african_union', 'Membre'),
  ('seychelles', 'org_african_union', 'Membre'),
  ('sierra-leone', 'org_african_union', 'Membre'),
  ('somalia', 'org_african_union', 'Membre'),
  ('sudan', 'org_african_union', 'Membre'),
  ('south-sudan', 'org_african_union', 'Membre'),
  ('tanzania', 'org_african_union', 'Membre'),
  ('chad', 'org_african_union', 'Membre'),
  ('togo', 'org_african_union', 'Membre'),
  ('tunisia', 'org_african_union', 'Membre'),
  ('zambia', 'org_african_union', 'Membre'),
  ('zimbabwe', 'org_african_union', 'Membre')
ON CONFLICT (countryid, organizationid) DO NOTHING; 