-- =====================================================
-- Script pour identifier les pays manquants
-- Comparaison avec les 195 pays souverains reconnus par l'ONU
-- =====================================================

-- Créer une table temporaire avec tous les pays souverains
CREATE TEMP TABLE pays_reference (
    nom VARCHAR(100),
    continent VARCHAR(50)
);

-- Insérer tous les pays souverains reconnus par l'ONU
INSERT INTO pays_reference (nom, continent) VALUES
-- Afrique (54 pays)
('Afrique du Sud', 'Afrique'),
('Algérie', 'Afrique'),
('Angola', 'Afrique'),
('Bénin', 'Afrique'),
('Botswana', 'Afrique'),
('Burkina Faso', 'Afrique'),
('Burundi', 'Afrique'),
('Cameroun', 'Afrique'),
('Cap-Vert', 'Afrique'),
('Comores', 'Afrique'),
('Congo', 'Afrique'),
('Côte d''Ivoire', 'Afrique'),
('Djibouti', 'Afrique'),
('Égypte', 'Afrique'),
('Érythrée', 'Afrique'),
('Éthiopie', 'Afrique'),
('Gabon', 'Afrique'),
('Gambie', 'Afrique'),
('Ghana', 'Afrique'),
('Guinée', 'Afrique'),
('Guinée équatoriale', 'Afrique'),
('Guinée-Bissau', 'Afrique'),
('Kenya', 'Afrique'),
('Lesotho', 'Afrique'),
('Libéria', 'Afrique'),
('Libye', 'Afrique'),
('Madagascar', 'Afrique'),
('Malawi', 'Afrique'),
('Mali', 'Afrique'),
('Maroc', 'Afrique'),
('Maurice', 'Afrique'),
('Mauritanie', 'Afrique'),
('Mozambique', 'Afrique'),
('Namibie', 'Afrique'),
('Niger', 'Afrique'),
('Nigeria', 'Afrique'),
('Ouganda', 'Afrique'),
('République centrafricaine', 'Afrique'),
('République démocratique du Congo', 'Afrique'),
('Rwanda', 'Afrique'),
('Sénégal', 'Afrique'),
('Seychelles', 'Afrique'),
('Sierra Leone', 'Afrique'),
('Somalie', 'Afrique'),
('Soudan', 'Afrique'),
('Soudan du Sud', 'Afrique'),
('Tanzanie', 'Afrique'),
('Tchad', 'Afrique'),
('Togo', 'Afrique'),
('Tunisie', 'Afrique'),
('Zambie', 'Afrique'),
('Zimbabwe', 'Afrique'),
('Eswatini', 'Afrique'),

-- Amérique du Nord (23 pays)
('Antigua-et-Barbuda', 'Amérique du Nord'),
('Bahamas', 'Amérique du Nord'),
('Barbade', 'Amérique du Nord'),
('Belize', 'Amérique du Nord'),
('Canada', 'Amérique du Nord'),
('Costa Rica', 'Amérique du Nord'),
('Cuba', 'Amérique du Nord'),
('Dominique', 'Amérique du Nord'),
('États-Unis', 'Amérique du Nord'),
('Grenade', 'Amérique du Nord'),
('Guatemala', 'Amérique du Nord'),
('Haïti', 'Amérique du Nord'),
('Honduras', 'Amérique du Nord'),
('Jamaïque', 'Amérique du Nord'),
('Mexique', 'Amérique du Nord'),
('Nicaragua', 'Amérique du Nord'),
('Panama', 'Amérique du Nord'),
('République dominicaine', 'Amérique du Nord'),
('Saint-Kitts-et-Nevis', 'Amérique du Nord'),
('Saint-Lucie', 'Amérique du Nord'),
('Saint-Vincent-et-les-Grenadines', 'Amérique du Nord'),
('Salvador', 'Amérique du Nord'),
('Trinité-et-Tobago', 'Amérique du Nord'),

-- Amérique du Sud (12 pays)
('Argentine', 'Amérique du Sud'),
('Bolivie', 'Amérique du Sud'),
('Brésil', 'Amérique du Sud'),
('Chili', 'Amérique du Sud'),
('Colombie', 'Amérique du Sud'),
('Équateur', 'Amérique du Sud'),
('Guyana', 'Amérique du Sud'),
('Paraguay', 'Amérique du Sud'),
('Pérou', 'Amérique du Sud'),
('Suriname', 'Amérique du Sud'),
('Uruguay', 'Amérique du Sud'),
('Venezuela', 'Amérique du Sud'),

-- Asie (48 pays)
('Afghanistan', 'Asie'),
('Arabie Saoudite', 'Asie'),
('Arménie', 'Asie'),
('Azerbaïdjan', 'Asie'),
('Bahreïn', 'Asie'),
('Bangladesh', 'Asie'),
('Bhoutan', 'Asie'),
('Birmanie', 'Asie'),
('Brunei', 'Asie'),
('Cambodge', 'Asie'),
('Chine', 'Asie'),
('Corée du Nord', 'Asie'),
('Corée du Sud', 'Asie'),
('Émirats arabes unis', 'Asie'),
('Géorgie', 'Asie'),
('Inde', 'Asie'),
('Indonésie', 'Asie'),
('Irak', 'Asie'),
('Iran', 'Asie'),
('Israël', 'Asie'),
('Japon', 'Asie'),
('Jordanie', 'Asie'),
('Kazakhstan', 'Asie'),
('Kirghizistan', 'Asie'),
('Koweït', 'Asie'),
('Laos', 'Asie'),
('Liban', 'Asie'),
('Malaisie', 'Asie'),
('Maldives', 'Asie'),
('Mongolie', 'Asie'),
('Myanmar', 'Asie'),
('Népal', 'Asie'),
('Oman', 'Asie'),
('Ouzbékistan', 'Asie'),
('Pakistan', 'Asie'),
('Philippines', 'Asie'),
('Qatar', 'Asie'),
('Singapour', 'Asie'),
('Sri Lanka', 'Asie'),
('Syrie', 'Asie'),
('Tadjikistan', 'Asie'),
('Taïwan', 'Asie'),
('Thaïlande', 'Asie'),
('Timor oriental', 'Asie'),
('Turkménistan', 'Asie'),
('Turquie', 'Asie'),
('Vietnam', 'Asie'),
('Yémen', 'Asie'),

-- Europe (44 pays)
('Albanie', 'Europe'),
('Allemagne', 'Europe'),
('Andorre', 'Europe'),
('Autriche', 'Europe'),
('Belgique', 'Europe'),
('Biélorussie', 'Europe'),
('Bosnie-Herzégovine', 'Europe'),
('Bulgarie', 'Europe'),
('Chypre', 'Europe'),
('Croatie', 'Europe'),
('Danemark', 'Europe'),
('Espagne', 'Europe'),
('Estonie', 'Europe'),
('Finlande', 'Europe'),
('France', 'Europe'),
('Grèce', 'Europe'),
('Hongrie', 'Europe'),
('Irlande', 'Europe'),
('Islande', 'Europe'),
('Italie', 'Europe'),
('Kosovo', 'Europe'),
('Lettonie', 'Europe'),
('Liechtenstein', 'Europe'),
('Lituanie', 'Europe'),
('Luxembourg', 'Europe'),
('Macédoine du Nord', 'Europe'),
('Malte', 'Europe'),
('Moldavie', 'Europe'),
('Monaco', 'Europe'),
('Monténégro', 'Europe'),
('Norvège', 'Europe'),
('Pays-Bas', 'Europe'),
('Pologne', 'Europe'),
('Portugal', 'Europe'),
('République tchèque', 'Europe'),
('Roumanie', 'Europe'),
('Royaume-Uni', 'Europe'),
('Russie', 'Europe'),
('Saint-Marin', 'Europe'),
('Serbie', 'Europe'),
('Slovaquie', 'Europe'),
('Slovénie', 'Europe'),
('Suisse', 'Europe'),
('Suède', 'Europe'),
('Ukraine', 'Europe'),
('Vatican', 'Europe'),

-- Océanie (14 pays)
('Australie', 'Océanie'),
('Fidji', 'Océanie'),
('Kiribati', 'Océanie'),
('Marshall', 'Océanie'),
('Micronésie', 'Océanie'),
('Nauru', 'Océanie'),
('Nouvelle-Zélande', 'Océanie'),
('Palaos', 'Océanie'),
('Papouasie-Nouvelle-Guinée', 'Océanie'),
('Salomon', 'Océanie'),
('Samoa', 'Océanie'),
('Tonga', 'Océanie'),
('Tuvalu', 'Océanie'),
('Vanuatu', 'Océanie');

-- Identifier les pays manquants
SELECT 
    pr.nom as pays_manquant,
    pr.continent
FROM pays_reference pr
LEFT JOIN country c ON pr.nom = c.nom
WHERE c.nom IS NULL
ORDER BY pr.continent, pr.nom;

-- Afficher le résumé par continent
SELECT 
    pr.continent,
    COUNT(pr.nom) as pays_manquants,
    COUNT(c.nom) as pays_presents,
    COUNT(pr.nom) + COUNT(c.nom) as total_attendu
FROM pays_reference pr
LEFT JOIN country c ON pr.nom = c.nom
GROUP BY pr.continent
ORDER BY pr.continent;

-- Afficher le total
SELECT 
    COUNT(pr.nom) as total_pays_manquants,
    COUNT(c.nom) as total_pays_presents,
    COUNT(pr.nom) + COUNT(c.nom) as total_attendu
FROM pays_reference pr
LEFT JOIN country c ON pr.nom = c.nom; 